# Generated by Django 3.2.3 on 2024-04-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodgramuser',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_followers_constratints',
        ),
        migrations.RemoveIndex(
            model_name='foodgramuser',
            name='user_index_fields',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='following_user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='foodgramuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foodgramuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddIndex(
            model_name='foodgramuser',
            index=models.Index(fields=['first_name', 'last_name'], name='user_index_fields'),
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_followers_constratints'),
        ),
    ]
