# Generated by Django 5.0.4 on 2024-04-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foodgramuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='role',
        ),
    ]
